"""Regression checks for active operational documentation."""

import re
from pathlib import Path


ROOT = Path(__file__).parents[1]
ACTIVE_DOCS = [ROOT / "README.md", ROOT / "ROADMAP.md", *sorted((ROOT / "docs").glob("*.md"))]


def test_active_markdown_local_links_resolve():
    broken = []

    for document in ACTIVE_DOCS:
        text = document.read_text(encoding="utf-8")
        for target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", text):
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            relative_path = target.split("#", 1)[0]
            if relative_path and not (document.parent / relative_path).exists():
                broken.append(f"{document.relative_to(ROOT)} -> {target}")

    assert broken == []


def test_sample_threshold_guidance_cannot_reverse_deletion_behavior():
    configuration_doc = (ROOT / "docs" / "CONFIGURATION.md").read_text(encoding="utf-8")

    assert "lower the threshold to `1`" in configuration_doc
    assert '"min_sample_size_mb": 5000' not in configuration_doc


def test_quality_docs_do_not_hardcode_volatile_test_totals():
    volatile_docs = [
        ROOT / "README.md",
        ROOT / "ROADMAP.md",
        ROOT / "docs" / "README.md",
        ROOT / "docs" / "QUALITY.md",
        ROOT / "docs" / "TECHNICAL.md",
    ]
    hardcoded_total = re.compile(r"`?\b\d{2,}`?\s+(?:passing\s+)?tests\b", re.IGNORECASE)

    offenders = [str(path.relative_to(ROOT)) for path in volatile_docs if hardcoded_total.search(path.read_text())]

    assert offenders == []


def test_active_docs_have_no_ai_tool_attribution():
    banned = re.compile(r"\b(codex|claude|chatgpt|cursor ai|generated by (?:ai|an? llm))\b", re.IGNORECASE)
    offenders = []
    for document in ACTIVE_DOCS:
        for line_no, line in enumerate(document.read_text(encoding="utf-8").splitlines(), start=1):
            if banned.search(line):
                offenders.append(f"{document.relative_to(ROOT)}:{line_no}: {line.strip()}")
    assert offenders == []


def test_safety_docs_match_current_default_limits():
    safety = (ROOT / "docs" / "SAFETY.md").read_text(encoding="utf-8")
    assert "default `20` levels" in safety
    assert "default `48` hours" in safety
